var scoreText,
	highscoreString, 
	highscoreText, 
	openingText, 
	spaceBar, 
	instructions, 
	mothership, 
	alien1, 
	alien2, 
	alien3, 
	scoreTable, 
	alienScores, 
	Menu = {
		preload: function() {
        game.load.bitmapFont("minecraftia", gameRoot + "assets/fonts/minecraftia.png", gameRoot + "assets/fonts/minecraftia.xml"), 
		game.load.image("mothership", gameRoot + "assets/images/mothership.png"), 
		game.load.spritesheet("alien1", gameRoot + "assets/images/alien1.png", 87.5, 70, 2), 
		game.load.spritesheet("alien2", gameRoot + "assets/images/alien2.png", 99.5, 70, 2), 
		game.load.spritesheet("alien3", gameRoot + "assets/images/alien3.png", 107, 70, 2)
    },
    create: function() {
        spaceBar = game.input.keyboard.addKey(Phaser.Keyboard.SPACEBAR), 
		game.input.onTap.addOnce(this.startGame, this), 
		spaceBar.onDown.addOnce(this.startGame, this), 
		mothership = game.add.sprite(240, 365, "mothership"), 
		(alien1 = game.add.sprite(249, 398, "alien1")).scale.setTo(.35, .35),
		alien1.frame = 1, 
		(alien2 = game.add.sprite(250, 428, "alien2")).scale.setTo(.35, .35), 
		(alien3 = game.add.sprite(247, 458, "alien3")).frame = 1,
		alien3.scale.setTo(.35, .35), 
		fontSize = 20,
		(scoreTable = game.add.bitmapText(game.width / 2, 340, "minecraftia", "SCORE TABLE", fontSize)).anchor.setTo(.5, .5), 
		alienScores = game.add.bitmapText(300, 365, "minecraftia", "= ? MYSTERY\n= 30 POINTS\n= 20 POINTS\n= 10 POINTS", fontSize), 
		(scoreText = game.add.bitmapText(20, 10, "minecraftia", "SCORE<1>\n0000")).fontSize = fontSize, 
		scoreText.fill = "#fff", 
		game.add.bitmapText(570, 10, "minecraftia", "SCORE<2>", fontSize), 
		game.add.bitmapText(555, 620, "minecraftia", "CREDIT 00", fontSize), 
		localStorage.hiScore || (localStorage.hiScore = "0000"), 
		highscoreString = "HI-SCORE\n",
		highscoreText = game.add.bitmapText(300, 10, "minecraftia", highscoreString + localStorage.hiScore, fontSize), 
		(openingText = game.add.bitmapText(game.width / 2, 160, "minecraftia", "404 'PAGE NOT FOUND' INVADERS\n\n", fontSize)).anchor.setTo(.5, .5), 
		instructions1 = game.add.bitmapText(game.width / 2, 210, "minecraftia", "LEFT/RIGHT KEYS/ARROWS TO MOVE", fontSize), 
		instructions1.anchor.setTo(.5, .5),
		instructions2 = game.add.bitmapText(game.width / 2, 250, "minecraftia", "TAP/SPACEBAR TO SHOOT", fontSize), 
		instructions2.anchor.setTo(.5, .5), toStart = game.add.bitmapText(game.width / 2, 580, "minecraftia", "START GAME WITH TAP/SPACEBAR", fontSize), 
		toStart.anchor.setTo(.5, .5)
    },
    startGame: function() {
        this.state.start("Game")
    }
};